server:
  port: 8081
# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.27.37:3306/vueadmin?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: 192.168.27.37
#  security:
#    user:
#      name: user
#      password: 111111
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
markerhub:
  jwt:
    header: Authorization
    expire: 604800 #7天，秒单位
    secret: ji8n3439n439n43ld9ne9343fdfer49h

#七牛云上传文件配置
qiniu:
  access-key: gP4XWxPuAMZMeVFeU83IW1mxv_FbFBLRDw94GGIZ
  secret-key: efCnmzcr4KfUji08zVfz2L4-PD4F8Ei0nfBuA2Ut
  bucket: yuque-hexo







